<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitbfd1d2fe4e919e560624941a258fd0e7
{
    public static $prefixLengthsPsr4 = array (
        'P' => 
        array (
            'Prokerala\\' => 10,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Prokerala\\' => 
        array (
            0 => __DIR__ . '/..' . '/prokerala/astrology-sdk/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitbfd1d2fe4e919e560624941a258fd0e7::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitbfd1d2fe4e919e560624941a258fd0e7::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInitbfd1d2fe4e919e560624941a258fd0e7::$classMap;

        }, null, ClassLoader::class);
    }
}
